### ISSUE TITLE
Provide method to supresss browse activity for some queues

### ISSUE THREAD

**Issue by rnikula** [Nastel/tnt4j-streams#19]
May be applicable beyond MQ but specifically, MQ provides 2 forms of MQGET, a destructive get and a browse (controlled by message get options).   Browsing can create a lot of messages since a common application model is to browse the entire queue looking for a specific message.   It may do this repeatedly over the course of time, potentially generating 1000s of message events.   In some cases, these events are useful but in many cases, they are just 'noise'.

**Comment by kausandr** [comment]
how we can identify such trace events and suppress them from streaming? 

Now trace stream can check trace operation and reason code to decide if it is relevant to stream (using properties `TraceOperations` and `ExcludedRC`.

**Comment by rnikula** [comment]
It would require some research of the activity events.   You can tell from the open (MQOO_BROWSE option) or from the get options (MQGMO_BROWSE_FIRST or MQGMO_BROWSE_NEXT).   Since you may not see the open, you would have to rely on the get options.

**Comment by kausandr** [comment]
So if: 
 * user configured not to process browse gets 
 * and trace event get options (param `MQIACF_GET_OPTIONS`) has any of `MQGMO_BROWSE_FIRST`, `MQGMO_BROWSE_NEXT` or `MQGMO_BROWSE_MSG_UNDER_CURSOR`

we may skip such traces, right?

**Comment by amavashev** [comment]
It has to be configuration based (all filtering), not hardcoded or implied since there are instances where someone wants to see browses. This applis to any event (pcf or non) how to fiter out whats coming in? Need a generic approach for filtering which works for this case as well. Example: RC != 2033, RC > 2033 or there could be multiple AND or ORs. Basically need a generic filtering capability.
