### ISSUE TITLE
Event messages from IIB seem te get lost

### ISSUE THREAD

**Issue by Jens1977** [Nastel/tnt4j-streams#24]
Sometimes event messages from IBM Integration Bus are not sent to jkoolcloud. 

Use-case:
I configured the TransactionStart and TransactionEnd events on the input node in the message-flow, so I expect 2 event message for every message I put on MQ.

Using RFHUtilc I first put 10 messages on MQ:
10.38.22 Message sent to MQTOP.IN length=303
10.38.21 Message sent to MQTOP.IN length=303
10.38.21 Message sent to MQTOP.IN length=303
10.38.21 Message sent to MQTOP.IN length=303
10.38.21 Message sent to MQTOP.IN length=303
10.38.21 Message sent to MQTOP.IN length=303
10.38.21 Message sent to MQTOP.IN length=303
10.38.20 Message sent to MQTOP.IN length=303
10.38.20 Message sent to MQTOP.IN length=303
10.38.20 Message sent to MQTOP.IN length=303

All 20 messages show up in jKool:
![image](https://cloud.githubusercontent.com/assets/7572279/23299105/842a7db6-fa80-11e6-8b37-ad2ced01e6bd.png)

Then, a couple of minutes later, I put another 10 messages on MQ:
10.43.28 Message sent to MQTOP.IN length=303
10.43.28 Message sent to MQTOP.IN length=303
10.43.28 Message sent to MQTOP.IN length=303
10.43.27 Message sent to MQTOP.IN length=303
10.43.27 Message sent to MQTOP.IN length=303
10.43.27 Message sent to MQTOP.IN length=303
10.43.27 Message sent to MQTOP.IN length=303
10.43.27 Message sent to MQTOP.IN length=303
10.43.26 Message sent to MQTOP.IN length=303
10.43.26 Message sent to MQTOP.IN length=303

This time, only 17 messages show up in jKool:
![image](https://cloud.githubusercontent.com/assets/7572279/23299195/de1a7812-fa80-11e6-9870-3ce12fab9825.png)

Trace-log:
[tnt4j-streams.zip](https://github.com/Nastel/tnt4j-streams/files/798917/tnt4j-streams.zip)

**Comment by kausandr** [comment]
JKool sometimes is processing received events for a longer time. So when you stream i.e. 20 events and refresh table just after streaming over - see only 15 records. But after refreshing table again after some period of time, table shows already all 20 records.

**Comment by Jens1977** [comment]
Even after waiting a long time before refresh, still table shows only 17 records.

**Comment by kausandr** [comment]
Check `logs/tnt4j-streams-activities.log` file. If it contains all 40 events you streamed - then need to contact Jkool guys (jerry) to check whats on they side. Maybe some of our events was correlated with ones you have sent previously and in this case new ones are not created, just updated data for older ones.

**Comment by Jens1977** [comment]
I checked the last 40 messages in tnt4j-streams-activities.log (corrid 956c5df4-fa64-11e6-85a1-7f0001010000-114 to 956c5df4-fa64-11e6-85a1-7f0001010000-133 subsequently).
When I query jKool for the first 20 messages (Get event where corrid='<corrid>'), I get 2 results per corrid in the table. For corrid=956c5df4-fa64-11e6-85a17f0001010000-124 I get no results, and for corrid=956c5df4-fa64-11e6-85a17f0001010000-125 I get only 1 result.

**Comment by kausandr** [comment]
So you have sent 40 events to JKool (streams made its job). JKool marged you last 20 events with previous ones depending on event data. Correlator values comes from IIB events data?

**Comment by Jens1977** [comment]
Sorry, I forgot to mention that for corrids 956c5df4-fa64-11e6-85a17f0001010000-126 to 956c5df4-fa64-11e6-85a17f0001010000-133, I do get 2 results per corrid in jKool. I'm not sure where the correlator values come from, but I suspect they come from IIB because for every message 2 events are emitted.

**Comment by kausandr** [comment]
Show me your `tnt-data-source.xml`.

These questions regarding how JKool handles incoming events should be addressed to JKool team. I'm not capable to answer this  :( My scope ends on what you see in `tnt4j-streams-activities.log` - this is `TNT4J-Streams` output to JKool.

**Comment by Jens1977** [comment]
[tnt-data-source.zip](https://github.com/Nastel/tnt4j-streams/files/799176/tnt-data-source.zip)

**Comment by kausandr** [comment]
yes, corellator is `/wmb:event/wmb:eventPointData/wmb:eventData/wmb:eventCorrelation/@wmb:localTransactionId`. so if last 20 events has some repeating from first 20 events - you have situation with events merging in JKool.

**Comment by Jens1977** [comment]
In tnt4j-streams-activities.log, every 2 events have the same correlation id. I have contacted support@jkoolcloud for further investigation. Thanks for your support.

**Comment by kausandr** [comment]
`every 2 events have the same correlation id` by this you mean:
 * events for same message put - then they refer to same message as as you said `so I expect 2 event message for every message I put on MQ`.
 * if first 20 events has same corresponding correlators in last 20 events - then it must be same data used to initiate first and last portion of events. `same data` - mean you are putting same messages to queue or something like this.

**Comment by Jens1977** [comment]
I understand, but all the messages put have a unique transaction id. For every message 2 events with the same correlation id are emitted and sent to jKool. In jKool all but some events are visible (I see 37 records for 20 messages). I'll wait for jkool support team, maybe they can tell me what has happened.

**Comment by kausandr** [comment]
provide them `tnt4j-streams-activities.log` so they can "replay" what you have been sending to jKool and see what happens.

**Comment by jbnas** [comment]
Let me describe the backend processing very briefly, to give you an idea of what to expect.  The backend never "merges" reported data into a single record.  EVERY event is recorded by backend, with each event being given a unique ID.  Events that share a correlator are "stitched", meaning they are put into the same activity, so backend will create an activity record, and mark it as the parent of the stitched events.  It's not exactly this simple, but since it looks like tnt4j-streams ALWAYS sends events, every operation reported by tnt4j-streams should wind up in the database.

That said, I've been doing some investigation and haven't found any specific problems related to this.  In importing the activities log, using SSL connection to jkool, I found that one of the messages failed with an SSL error, and as a result, jkool closed the connection.  I don't see any errors that I can contribute to your streaming, but will continue to investigate.  According to jkool metrics, every event that was received by jkool was written to database, and is available for query.

One thing that should be investigated is how tnt4j-streams handles broken connections with jkool service.  If tnt4j-streams behaves like old direct feed probe, then it opens a connection to jkool and keeps it open.  However, jkool has logic that if a connection is idle for a defined length of time (currently 5 minutes), then jkool will close the connection.  There is a flaw in direct feed probe that the first write it attempts to the closed connection gets lost, since the write fails, and it reestablishes the connection, but does not retry the message, but goes on to the next one.

**Comment by amavashev** [comment]
@kausandr  please investigate connection handling in tnt4j-streams as per @jbnas  comments. It is possible events might be dropped due to connection failures.

**Comment by kausandr** [comment]
Before sending jkool event streams does this:
```java
if (!tracker.isOpen()) {
    tracker.open();
}
```

**Comment by jbnas** [comment]
`tracker.isOpen()` is only checking a flag which indicates that `Tracker.open()` was called.  If remote end closes socket, local end will not know and think socket is still open until it attempts to write.  What needs to be done is to catch any `IOException`s on writing and assume that it's because connection is closed.  What you should then do is explicitly close the tracker, so that internal tracker stuff is cleaned up, then attempt to reopen it and retry the write.  If reconnect fails, or write retry fails, then propagate error.

Also, not sure how true this is on Unix, but definitely true on Windows, if you close the connection immediately after the last write, the socket will get closed before all data is written, so data could get lost there.

Looking at what I believe are timestamps in the 2 separate runs:

```
First test ended at: 10.38.20 Message sent to MQTOP.IN length=303
Second test started at: 10.43.28 Message sent to MQTOP.IN length=303
```

There was a 5 minute gap between these 2 tests, so jkool service could have closed the connection between the 2 tests, so messages could be lost here if reconnect logic is incorrect.  If this in fact the case, I would expect 1 message per sink-thread to be lost.  So, if tnt4j-streams is using a BufferedSink with 3 threads, that could explain the 3 lost messages between these 2 tests.

We could test this out simply. Restart tnt4j-streams and run a test using a block of 10 events.  Repeat this test several times with 2 minutes between tests and see if nothing gets lost.  Then wait 10 minutes and run another test and then see if something is lost.  If the lose occurs only after the 10 minute wait, then it points to error logic on tnt4j-streams/tnt4j-api/jesl side.

**Comment by Jens1977** [comment]
@jbnas, it seems you are right! I ran the tests you suggested and the results are as you predicted. I first ran 5 tests with blocks of 10 messages, two minutes apart and no messages got lost (100 records in jKool). Then I waited for 10 minutes and ran another block of 10 messages, now only 17 records are visible in jKool.

[tnt4j-streams-activities.zip](https://github.com/Nastel/tnt4j-streams/files/803088/tnt4j-streams-activities.zip)

**Comment by kausandr** [comment]
Communication failure handling fixed.

**Comment by Jens1977** [comment]
I have tested the fix.
2 observations:
1. Now, after waiting longer than 5 minutes between tests, 2 events from the second test are missing in stead of 3. So still missing data...
2. The message field in the jKool table for the transactionEnd records is empty, where before it was filled with base24 encoded message, as I configured.
Could you please reopen the issue?

**Comment by kausandr** [comment]
1. Can you give us your logs? Both straem and activities
2. Because of #24 now you get no message field data if none was parsed from RAW activity data.

**Comment by Jens1977** [comment]
[tnt4j-streams.zip](https://github.com/Nastel/tnt4j-streams/files/809971/tnt4j-streams.zip)

**Comment by kausandr** [comment]
So your `END` event does not contain data you are mapping to `Message` field - `wmb:bitstream`.

**Comment by kausandr** [comment]
You are streaming to `test.jkoolcloud.com` or `jkool.jkoolcloud.com`?

How many entries you see for these correlators: `414d5120494942514d20202020202020fb8eb558b2c85c25` and `414d5120494942514d20202020202020fb8eb558c7c85c25`? 

Events having these correlators have been facing connection problems and been resent. It you have 2 for every one - then i can assure you that we have no re-connection issues now on streams side.

**Comment by Jens1977** [comment]
I am streaming to jkool.jkoolcloud.com
For the 2 correlators you mentioned I have 2 entries for both, however I have no entries for corrid 414d5120494942514d20202020202020fb8eb558c6c85c25

**Comment by kausandr** [comment]
There is bug in JESL/Apache HC API. It proves your finding that you are missing events before streams has detected connection to Cloud is broken.

**Comment by Jens1977** [comment]
I saw there was an update on JESL today, zo I pulled it from GitHub and recompiled.
I ran the same tests, but now after 5 minutes of idle time no events are posted to jKool. Also tnt4j-streams-activities.log is not updated...

**Comment by kausandr** [comment]
Not fixed yet.

**Comment by kausandr** [comment]
Fixes made in both streams and [JESL][../JESL].

**Comment by kausandr** [comment]
@Jens1977 is streams not loosing data now?

**Comment by Jens1977** [comment]
@kausandr I have tested the fix and it is working fine! All data is visible in jKool.

**Comment by kausandr** [comment]
very well.
